# Generated by Django 3.0.8 on 2020-07-09 05:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameraimage', models.ImageField(default='', upload_to='camera')),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=200)),
                ('quantity', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('place', models.CharField(default='', max_length=200)),
                ('contactnumber', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='userregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.ImageField(default='', upload_to='user')),
                ('username', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('pincode', models.CharField(default='', max_length=200)),
                ('number', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='photographerboooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.photographer')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200)),
                ('quantity', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='', max_length=200)),
                ('cameraId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.userregister')),
            ],
        ),
    ]
