# Generated by Django 3.0.8 on 2020-07-05 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.date(2020, 7, 5)),
        ),
    ]
