# Generated by Django 3.0.8 on 2020-07-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='cameramanname',
        ),
        migrations.AddField(
            model_name='photographer',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='photographerboooking',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='photographerboooking',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
