# Generated by Django 3.0.8 on 2020-07-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerboooking',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
