# Generated by Django 3.0.8 on 2020-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20200711_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='camera',
            field=models.CharField(default='', max_length=200),
        ),
    ]
