# Generated by Django 3.0.8 on 2020-07-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_userregister_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cameramanname',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='camera',
        ),
    ]
