# Generated by Django 3.0.8 on 2020-07-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20200710_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
